export const CHANGE_MODE = "CHANGE_MODE";
export const CHANGE_STYLE_DARK = "CHANGE_STYLE_DARK";
export const CHANGE_STYLE_LIGHT = "CHANGE_STYLE_LIGHT";

export const SEARCH_MOVIES_BY_INPUT = "SEARCH_MOVIES_BY_INPUT";
export const SEARCH_MOVIES_BY_SUBTYPE = "SEARCH_MOVIES_BY_SUBTYPE";
export const SEARCH_MOVIES_BY_INPUT_SUCCESS = "SEARCH_MOVIES_BY_TYPE_SUCCESS";
export const SEARCH_MOVIES_BY_SUBTYPE_SUCCESS = "SEARCH_MOVIES_BY_SUBTYPE_SUCCESS";
export const SEARCH_MOVIES_CHANGE_PAGE = "SEARCH_MOVIES_CHANGE_PAGE";
export const SEARCH_MOVIES_CHANGE_PAGE_SUCCESS = "SEARCH_MOVIES_CHANGE_PAGE_SUCCESS";
export const SEARCH_TYPE_RESET = "SEARCH_TYPE_RESET";

export const SEARCH_MOVIES_RESET = "SEARCH_MOVIES_RESET";

export const TRAILER_INIT = "TRAILER_INIT";
export const TRAILER_OPEN = "TRAILER_OPEN";
export const TRAILER_CLOSE = "TRAILER_CLOSE";