export const CHANGE_MODE = "CHANGE_MODE";
export const CHANGE_STYLE_DARK = "CHANGE_STYLE_DARK";
export const CHANGE_STYLE_LIGHT = "CHANGE_STYLE_LIGHT";

export const GET_GENRES = "GET_GENRES";
export const SET_MOVIES = "SET_MOVIES";
export const SEARCH_MOVIES_BY_INPUT = "SEARCH_MOVIES_BY_INPUT";
export const SEARCH_MOVIES_BY_SUBTYPE = "SEARCH_MOVIES_BY_SUBTYPE";
export const SEARCH_MOVIES_BY_INPUT_SUCCESS = "SEARCH_MOVIES_BY_TYPE_SUCCESS";
export const SEARCH_MOVIES_BY_SUBTYPE_SUCCESS = "SEARCH_MOVIES_BY_SUBTYPE_SUCCESS";
export const SEARCH_MOVIES_CHANGE_PAGE = "SEARCH_MOVIES_CHANGE_PAGE";
export const SEARCH_MOVIES_CHANGE_PAGE_SUCCESS = "SEARCH_MOVIES_CHANGE_PAGE_SUCCESS";
export const SEARCH_TYPE_RESET = "SEARCH_TYPE_RESET";
export const SEARCH_MODE_TOGGLE = "SEARCH_MODE_TOGGLE";
export const INITIAL_SEARCH = "INITIAL_SEARCH";

export const SEARCH_MOVIES_RESET = "SEARCH_MOVIES_RESET";

export const TRAILER_INIT = "TRAILER_INIT";
export const TRAILER_OPEN = "TRAILER_OPEN";
export const TRAILER_CLOSE = "TRAILER_CLOSE";


export const SET_TYPE_AND_ID = "SET_TYPE_AND_ID";
export const SET_MOVIE = "SET_MOVIE";
export const SET_SIMILAR_MOVIES = "SET_SIMILAR_MOVIES";
export const SET_CREDITS = "SET_CREDITS";
export const RESET_DATA = "RESET_DATA";
export const RESET_SIMILAR_MOVIES = "RESET_SIMILAR_MOVIES";